language: ruby
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: bkelly@pivotal.io
  password:
    secure: PsA1Y/gyhnPZYAbnUO4pyhY2L/IF/NdBYVb4n6M0MOprwZfMRD+HdwYSsIDV3Y0LGdeF60IUSTqkMExqLo1f2t6oNLiqIP6seCkSItOjMgigWGIJOMTdI3ZNzemStWZmlZGYg4BynLuclc9lI9hXEv/s4rthN4oGarYh5i+23Zk=
  organization: pivotallabs
  space: pivotal-life
  app: pivotal-life-staging
  on:
    repo: pivotal/pivotal-life
